### ISSUE TITLE
Giveaway 2.0

### ISSUE THREAD

**Issue by MrWakeCZ** [CorgiBot/CorgiBot#46]
Současný giveaway již nesplňuje požadovano kvalitu, navíc částečně nefunguje...

## Požadavky
- [x] Příkaz `c!giveaway 1h30m | Výhra v loterii | 2 | :smile:`
- [x] Automatický ukládání/načítání při restartu
- [ ] Možnost rerollu (znovu vyhodnocení)

**Comment by MrFriggo** [comment]
A co znamená u toho příkazu ta "2" a ten smile?

**Comment by MrWakeCZ** [comment]
1. je čas, 2. je výhra, 3. je počet výherů, 4. vlastni emoji

**Comment by MrFriggo** [comment]
Takže to na to vlastní emoji musí kliknout pro připojení 😮 Ještě bych tam přidal možnost, že by výhercovi poslalo do DM výhru, třeba kdyby to byl giveaway o steam klíč, tak by to po ukončení poslalo výherci do DM ten klíč.

**Comment by Brumikosaurus** [comment]
Tuhle funkci bych taky ocenil

**Comment by MrWakeCZ** [comment]
Nu bylo by to super, ale zase nechci aby Corgi ukládal nějaký data, který nejsou "jeho". Př. třeba ty klíče, který mají nějakou hodnotu ve výsledku.
